version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: minuto-estoico-api
    restart: unless-stopped
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      PORT: 3021
      NODE_ENV: production
      FRONTEND_URL: ${FRONTEND_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minutoestoico-api.rule=Host(`minutoestoico.nico.dev.br`) && PathPrefix(`/api`)"
      - "traefik.http.routers.minutoestoico-api.entrypoints=websecure"
      - "traefik.http.routers.minutoestoico-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.minutoestoico-api.loadbalancer.server.port=3021"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: minuto-estoico-web
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      PORT: 3020
      NODE_ENV: production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minutoestoico.rule=Host(`minutoestoico.nico.dev.br`)"
      - "traefik.http.routers.minutoestoico.entrypoints=websecure"
      - "traefik.http.routers.minutoestoico.tls.certresolver=letsencrypt"
      - "traefik.http.services.minutoestoico.loadbalancer.server.port=3020"
