/**
 * Base de dados inicial de citações filosóficas estoicas.
 * Usada tanto pelo seed manual (prisma/seed.ts) quanto pelo
 * DatabaseSeederService no auto-seed da primeira inicialização.
 */
export const QUOTES_DATA = [
  // ── MARCO AURÉLIO ──────────────────────────────────────────
  {
    text: 'Você tem poder sobre sua mente, não sobre os acontecimentos externos. Perceba isso e encontrará força.',
    author: 'Marco Aurélio',
    reflection: 'A maior liberdade que possuímos não está nos eventos que nos rodeiam, mas na forma como escolhemos reagir a eles. Cada vez que atribuímos nossa paz de espírito a fatores externos, cedemos o controle da nossa vida. Hoje, pratique separar o que você pode controlar daquilo que não pode — e dirija sua energia apenas ao primeiro.',
    category: 'Autoconhecimento',
    tags: ['mente', 'controle', 'força', 'liberdade'],
    language: 'pt',
  },
  {
    text: 'Perde o tempo quem se ocupa com o que os outros pensam, falam ou fazem.',
    author: 'Marco Aurélio',
    reflection: 'A atenção é um recurso finito e precioso. Quando a desperdiçamos julgando os outros ou preocupando-nos com seus julgamentos sobre nós, esvaziamos a energia que poderíamos destinar ao nosso próprio crescimento. Redirecione o olhar para dentro: o único terreno que realmente pode ser cultivado é o seu próprio caráter.',
    category: 'Foco',
    tags: ['foco', 'tempo', 'atenção', 'indiferença'],
    language: 'pt',
  },
  {
    text: 'Muito pouco é necessário para uma vida feliz; tudo está dentro de você, na sua maneira de pensar.',
    author: 'Marco Aurélio',
    reflection: 'A felicidade não é a soma de conquistas externas. É o produto da clareza interior. Pessoas que acumulam riquezas, títulos e reconhecimentos, mas vivem em conflito consigo mesmas, não encontram sossego. Enquanto aqueles que dominam seus pensamentos e emoções descobrem uma abundância que ninguém pode tomar. A raiz da vida plena está na sua forma de encarar o mundo.',
    category: 'Sabedoria',
    tags: ['felicidade', 'pensamento', 'simplicidade', 'interior'],
    language: 'pt',
  },
  {
    text: 'Quando acordar de manhã, pense no precioso privilégio que é estar vivo — respirar, pensar, desfrutar, amar.',
    author: 'Marco Aurélio',
    reflection: 'A gratidão começa antes mesmo do primeiro passo do dia. Acordar com consciência do presente — da respiração, dos pensamentos, das pessoas que amamos — transforma um ato rotineiro em um ato sagrado. O hábito de reconhecer o privilégio da existência logo ao despertar muda completamente a tonalidade do dia que está por vir.',
    category: 'Gratidão',
    tags: ['gratidão', 'vida', 'presença', 'manhã'],
    language: 'pt',
  },
  {
    text: 'A melhor vingança é não se tornar igual ao seu inimigo.',
    author: 'Marco Aurélio',
    reflection: 'Quando alguém nos faz mal, a tentação de retribuir com a mesma moeda é poderosa. Mas ao agirmos com rancor e malícia, deixamos de ser quem somos para nos tornar o que desprezamos. A verdadeira superioridade moral não está na vitória sobre o outro, mas na recusa de abrir mão dos próprios valores, mesmo sob pressão.',
    category: 'Virtude',
    tags: ['virtude', 'perdão', 'caráter', 'autocontrole'],
    language: 'pt',
  },
  {
    text: 'Nunca esteja com pressa. Nunca seja apático. Nunca seja ansioso. Nunca seja evasivo. Seja senhor de si mesmo.',
    author: 'Marco Aurélio',
    reflection: 'O autodomínio é o centro gravitacional de uma vida bem vivida. Agir com pressa produz erros; a apatia nos afasta do progresso; a ansiedade obscurece o julgamento; a evasão adia o inevitável. Ser senhor de si mesmo não é uma questão de perfeição, mas de presença e intenção deliberada em cada momento.',
    category: 'Autodisciplina',
    tags: ['autodomínio', 'equilíbrio', 'disciplina', 'presença'],
    language: 'pt',
  },
  {
    text: 'Trate os obstáculos como trampolins. O impedimento é o caminho.',
    author: 'Marco Aurélio',
    reflection: 'O estoicismo nos ensina que não é possível eliminar os obstáculos da vida, mas é possível transformar nossa relação com eles. Cada barreira contém, embutida em sua resistência, uma oportunidade de fortalecimento. Quando paramos de lutar contra o que não podemos mudar e começamos a encontrar o caminho através dele, somos maiores do que o problema.',
    category: 'Resiliência',
    tags: ['resiliência', 'obstáculo', 'crescimento', 'adversidade'],
    language: 'pt',
  },
  {
    text: 'Se não é certo, não o faças; se não é verdade, não o digas.',
    author: 'Marco Aurélio',
    reflection: 'A integridade pode ser reduzida a duas perguntas simples: Isto é correto? Isto é verdadeiro? Quando tornamos essas perguntas um filtro habitual para nossas ações e palavras, deixamos de agir por impulso ou conveniência e passamos a agir por princípio. É nessa consistência silenciosa que o caráter se forma.',
    category: 'Virtude',
    tags: ['integridade', 'verdade', 'ética', 'caráter'],
    language: 'pt',
  },
  {
    text: 'O homem deve ser imperturbável diante das coisas alheias à sua vontade.',
    author: 'Marco Aurélio',
    reflection: 'A paz interior não depende da ausência de caos ao redor, mas da capacidade de permanecer firme enquanto ele ocorre. Treinar a imperturbabilidade não é cultivar indiferença — é construir uma âncora interna que mantém o julgamento claro e a ação serena, mesmo quando as circunstâncias tentam nos desviar.',
    category: 'Resiliência',
    tags: ['imperturbabilidade', 'equanimidade', 'serenidade', 'controle'],
    language: 'pt',
  },
  {
    text: 'Aja bem, mesmo que não espere reconhecimento.',
    author: 'Marco Aurélio',
    reflection: 'A virtude autêntica não depende de audiência. Quando fazemos o bem esperando recompensa ou reconhecimento, nossa bondade é transacional. Quando fazemos o bem porque é quem somos — independentemente de ser visto ou valorizado —, construímos um caráter sólido que não oscila com os ventos da aprovação social.',
    category: 'Virtude',
    tags: ['virtude', 'reconhecimento', 'caráter', 'integridade'],
    language: 'pt',
  },
  {
    text: 'Medita sobre a morte todos os dias e viverás livremente.',
    author: 'Marco Aurélio',
    reflection: 'Memento mori — lembre-se de que você vai morrer — não é uma prática mórbida, mas libertadora. Quando nos lembramos da nossa finitude, o supérfluo perde peso e o essencial ganha urgência. As conversas que postergamos, o amor que guardamos, os projetos que adiamos — tudo isso se ilumina com outra clareza quando lembramos que o tempo é finito.',
    category: 'Tempo',
    tags: ['morte', 'finitude', 'urgência', 'liberdade'],
    language: 'pt',
  },

  // ── SÊNECA ─────────────────────────────────────────────────
  {
    text: 'Não é o homem que tem pouco que é pobre, mas o que deseja mais.',
    author: 'Sêneca',
    reflection: 'A pobreza real não é definida pelo que temos, mas pela distância entre o que temos e o que desejamos. Um homem rico pode ser o mais pobre de todos se sua ambição superar sempre suas posses. Já aquele que aprende a se satisfazer com o suficiente descobre uma riqueza que nunca pode ser roubada ou perdida.',
    category: 'Sabedoria',
    tags: ['riqueza', 'desejo', 'suficiência', 'contentamento'],
    language: 'pt',
  },
  {
    text: 'Enquanto adiamos, a vida passa.',
    author: 'Sêneca',
    reflection: 'O adiamento é o maior ladrão de tempo que existe. Adiamos conversas importantes, projetos significativos, mudanças necessárias — na ilusão de que haverá um momento melhor. Mas Sêneca nos lembra que esse momento nunca chega por conta própria: ele precisa ser escolhido, agora, com a vida que temos.',
    category: 'Tempo',
    tags: ['tempo', 'procrastinação', 'urgência', 'vida'],
    language: 'pt',
  },
  {
    text: 'Comece. Aquele que inicia já fez metade da tarefa.',
    author: 'Sêneca',
    reflection: 'O maior obstáculo para a maioria dos nossos objetivos não é a falta de habilidade ou recurso — é a resistência ao primeiro passo. Uma vez que nos colocamos em movimento, o impulso nos carrega. O perfeccionismo e o medo do fracasso nos paralisam antes de começar. Hoje, comece algo que você tem adiado. A segunda metade virá naturalmente.',
    category: 'Persistência',
    tags: ['início', 'ação', 'procrastinação', 'persistência'],
    language: 'pt',
  },
  {
    text: 'A gratidão é a maior das virtudes e a mãe de todas as outras.',
    author: 'Sêneca',
    reflection: 'Quem pratica a gratidão genuína dificilmente se perde na inveja, no rancor ou na amargura — porque está constantemente se lembrando do que possui, em vez de focar no que falta. A gratidão não é ingenuidade: é uma postura filosófica que reconhece o valor do presente e transforma a percepção de toda a existência.',
    category: 'Gratidão',
    tags: ['gratidão', 'virtude', 'perspectiva', 'felicidade'],
    language: 'pt',
  },
  {
    text: 'Erre pelo lado do excesso de coragem — e você errará menos do que pelo lado do excesso de cautela.',
    author: 'Sêneca',
    reflection: 'A cautela excessiva é uma forma silenciosa de covardia. Ela nos mantém seguros, mas nos priva de crescimento, de novas experiências e de versões mais corajosas de nós mesmos. Sêneca não prega a imprudência — mas lembra que uma vida vivida com excesso de hesitação desperdiça mais do que uma vida vivida com excesso de ousadia.',
    category: 'Coragem',
    tags: ['coragem', 'risco', 'audácia', 'crescimento'],
    language: 'pt',
  },
  {
    text: 'É de tolos esperar o que o futuro reserva; o sábio antecipa as dificuldades.',
    author: 'Sêneca',
    reflection: 'A premeditação das adversidades — premeditatio malorum — é um exercício central no estoicismo. Imaginar os desafios antes que ocorram não é pessimismo: é preparação. Quem antecipa as dificuldades reage com menos pânico, age com mais clareza e não é derrubado pela surpresa. A mente treinada para o pior é a mais capaz de lidar com o real.',
    category: 'Sabedoria',
    tags: ['antecipação', 'preparação', 'sabedoria', 'adversidade'],
    language: 'pt',
  },
  {
    text: 'Tudo é alheio; somente o tempo é nosso.',
    author: 'Sêneca',
    reflection: 'Posses, reputação, saúde, relacionamentos — tudo pode ser tirado de nós. O único recurso verdadeiramente nosso é o tempo que nos é dado. E mesmo assim o desperdiçamos em trivialidades, em rancores, em horas ociosas. Sêneca nos convoca a assumir a custódia do nosso tempo com a seriedade que daríamos a um tesouro insubstituível.',
    category: 'Tempo',
    tags: ['tempo', 'prioridade', 'vida', 'consciência'],
    language: 'pt',
  },
  {
    text: 'Recolha-se em si mesmo o máximo possível.',
    author: 'Sêneca',
    reflection: 'Num mundo que nos puxa constantemente para fora — notificações, opiniões alheias, demandas infinitas — o ato de recuar para dentro de si é um ato radical. O silêncio interior não é fuga; é reencontro. É no recolhimento que ouvimos nossa própria voz, reconhecemos nossos valores e tomamos decisões verdadeiramente nossas.',
    category: 'Autoconhecimento',
    tags: ['introspecção', 'silêncio', 'autoconhecimento', 'presença'],
    language: 'pt',
  },
  {
    text: 'Não há vento favorável para quem não sabe para onde vai.',
    author: 'Sêneca',
    reflection: 'Clareza de propósito é o primeiro requisito de qualquer jornada significativa. Sem saber aonde queremos chegar, qualquer caminho nos parece tão bom quanto outro — e nenhum nos leva a lugar algum. Definir com honestidade o que realmente importa para você é a bússola que transforma movimento em progresso.',
    category: 'Foco',
    tags: ['propósito', 'direção', 'clareza', 'objetivo'],
    language: 'pt',
  },
  {
    text: 'O ser humano sofre mais na imaginação do que na realidade.',
    author: 'Sêneca',
    reflection: 'A mente humana tem uma capacidade extraordinária de amplificar o que teme. Catástrofes imaginárias frequentemente superam em intensidade os problemas reais. Quando percebemos que grande parte do nosso sofrimento é fabricado pela imaginação — não pela experiência —, podemos questionar nossas narrativas e encontrar um solo mais firme sob nossos pés.',
    category: 'Autoconhecimento',
    tags: ['imaginação', 'sofrimento', 'medo', 'realidade'],
    language: 'pt',
  },
  {
    text: 'Trate cada dia como uma vida completa em si mesma.',
    author: 'Sêneca',
    reflection: 'E se este dia fosse tudo o que restasse? Não para viver com angústia ou pressa, mas com presença e intenção. Quando comprimimos nossa visão ao dia de hoje, as trivialidades perdem força e o que realmente importa se ilumina. Uma vida vivida como uma série de dias plenos é, no fim, uma vida muito bem vivida.',
    category: 'Tempo',
    tags: ['presente', 'dia', 'intenção', 'vida'],
    language: 'pt',
  },

  // ── EPICTETO ───────────────────────────────────────────────
  {
    text: 'Não exija que as coisas aconteçam como você deseja. Deseje as coisas como elas acontecem e você será feliz.',
    author: 'Epicteto',
    reflection: 'A diferença entre sofrimento e serenidade frequentemente reside numa única mudança de perspectiva: parar de exigir que a realidade se dobre aos nossos desejos e começar a desejar o que a realidade nos oferece. Isso não é resignação — é a sabedoria de reconhecer que a luta contra o inevitável nos cansa, enquanto a aceitação consciente nos liberta para agir com eficácia.',
    category: 'Aceitação',
    tags: ['aceitação', 'felicidade', 'desejo', 'realidade'],
    language: 'pt',
  },
  {
    text: 'Dos homens, uns são livres e outros escravos, não pelo nascimento, mas pelo caráter.',
    author: 'Epicteto',
    reflection: 'A liberdade que Epicteto valorizava — ele próprio nascido escravo — não era a liberdade física, mas a liberdade interior. Um homem livre pode ser escravo dos seus vícios, medos e opiniões alheias. Um escravo pode ser internamente livre ao manter sua dignidade, seus princípios e o domínio dos próprios julgamentos. O verdadeiro cativeiro mora dentro, não fora.',
    category: 'Virtude',
    tags: ['liberdade', 'caráter', 'dignidade', 'estoicismo'],
    language: 'pt',
  },
  {
    text: 'É impossível que um homem aprenda o que pensa que já sabe.',
    author: 'Epicteto',
    reflection: 'A arrogância intelectual é o maior obstáculo ao crescimento. Quando acreditamos que já sabemos, fechamos a mente para novas perspectivas, evidências e ensinamentos. A mente verdadeiramente aberta é aquela que, quanto mais aprende, mais reconhece o quanto ainda ignora — e por isso nunca para de crescer.',
    category: 'Sabedoria',
    tags: ['humildade', 'aprendizado', 'abertura', 'crescimento'],
    language: 'pt',
  },
  {
    text: 'Temos dois ouvidos e uma boca, para que ouçamos mais e falemos menos.',
    author: 'Epicteto',
    reflection: 'Escutar com genuína atenção é uma das habilidades mais raras e mais valiosas que um ser humano pode desenvolver. A maioria de nós escuta apenas para responder — não para compreender. Quando silenciamos nosso monólogo interior e realmente ouvimos os outros, absorvemos perspectivas que nos enriquecem e construímos vínculos mais profundos.',
    category: 'Sabedoria',
    tags: ['escuta', 'humildade', 'comunicação', 'aprendizado'],
    language: 'pt',
  },
  {
    text: 'Ocupe-se com as coisas que estão dentro da sua capacidade e aceite o resto como ele é.',
    author: 'Epicteto',
    reflection: 'A dicotomia do controle é o fundamento do pensamento estoico: separar o que depende de nós daquilo que não depende. Depositar energia, ansiedade e esperança naquilo que não controlamos é uma aposta sempre perdida. Mas direcionar toda a atenção e esforço para o que genuinamente está em nosso poder é o caminho mais seguro para resultados reais e para a paz de espírito.',
    category: 'Aceitação',
    tags: ['controle', 'aceitação', 'foco', 'serenidade'],
    language: 'pt',
  },
  {
    text: 'A riqueza consiste não em ter muito, mas em ter o suficiente.',
    author: 'Epicteto',
    reflection: 'A corrida pelo "mais" é interminável porque o ponto de chegada sempre recua. Quem aprende a reconhecer o suficiente descobre que já é rico. Não pela quantidade que possui, mas pela qualidade com que aprecia o que tem. Essa percepção não elimina a ambição, mas a calibra — direcionando-a para o que realmente enriquece a vida.',
    category: 'Gratidão',
    tags: ['suficiência', 'contentamento', 'riqueza', 'gratidão'],
    language: 'pt',
  },
  {
    text: 'A saúde da mente está em poder aceitar o que não pode ser mudado.',
    author: 'Epicteto',
    reflection: 'Resistir ao inevitável não o elimina — apenas nos desgasta. A aceitação que Epicteto pregava não é passividade, mas clareza: reconhecer o que está além do nosso controle nos libera para investir completamente no que está dentro dele. Essa distinção — simples de entender, difícil de praticar — é a raiz da saúde mental estoica.',
    category: 'Aceitação',
    tags: ['aceitação', 'saúde mental', 'equanimidade', 'controle'],
    language: 'pt',
  },
  {
    text: 'Cada amanhecer é um convite para simplificar a sua vida.',
    author: 'Epicteto',
    reflection: 'O novo dia oferece uma lousa quase em branco. Antes de preenchê-la com as mesmas preocupações, as mesmas distrações e os mesmos padrões de ontem, há uma janela de oportunidade: escolher o que realmente merece espaço. A simplicidade não é alcançada uma vez — é escolhida, de novo, a cada manhã.',
    category: 'Autodisciplina',
    tags: ['manhã', 'simplicidade', 'escolha', 'renovação'],
    language: 'pt',
  },
  {
    text: 'Guarda sempre em mente que tudo muda e que em breve não existirás — nem aquilo que contemplas.',
    author: 'Epicteto',
    reflection: 'A impermanência não é uma ameaça — é um convite. Quando aceitamos que tudo passa — as alegrias, as dores, as fases, as pessoas — paramos de nos agarrar desesperadamente ao que não pode ser retido e começamos a viver com mais presença e leveza. O que contemplamos hoje é precioso exatamente porque é passageiro.',
    category: 'Tempo',
    tags: ['impermanência', 'tempo', 'presença', 'mortalidade'],
    language: 'pt',
  },

  // ── ZENÃO E OUTROS ESTOICOS ────────────────────────────────
  {
    text: 'A felicidade é uma boa jornada, não um destino a alcançar.',
    author: 'Zenão de Cítio',
    reflection: 'Quando postergamos a felicidade para quando tivermos mais — mais dinheiro, mais reconhecimento, mais tempo — transformamos a vida em uma longa sala de espera. A sabedoria estoica nos lembra que a felicidade é vivida no processo: na atenção ao que fazemos agora, na qualidade com que o fazemos e na virtude com que nos relacionamos com os outros ao longo do caminho.',
    category: 'Sabedoria',
    tags: ['felicidade', 'processo', 'jornada', 'presença'],
    language: 'pt',
  },
  {
    text: 'A virtude é o único bem verdadeiro.',
    author: 'Zenão de Cítio',
    reflection: 'Para os estoicos, a virtude — sabedoria, justiça, coragem e moderação — era o único bem que não podia ser tirado, perdido ou deteriorado. Tudo o mais — riqueza, saúde, reputação — eram indiferentes: podiam ser úteis ou prejudiciais dependendo de como os usávamos. Essa ideia nos liberta: o que realmente importa já está ao nosso alcance.',
    category: 'Virtude',
    tags: ['virtude', 'bem', 'estoicismo', 'sabedoria'],
    language: 'pt',
  },
  {
    text: 'A calma é a forma mais elevada de autocontrole.',
    author: 'Provérbio Estoico',
    reflection: 'Manter a serenidade diante da pressão não é uma habilidade inata — é conquistada. A calma é o que permite ao cirurgião operar, ao líder decidir e ao pensador enxergar o que outros não veem. Cultivá-la diariamente — por meio da meditação, da respiração consciente, da reflexão — é um dos investimentos mais rentáveis que podemos fazer.',
    category: 'Autodisciplina',
    tags: ['calma', 'autocontrole', 'serenidade', 'equilíbrio'],
    language: 'pt',
  },

  // ── SÓCRATES / PLATÃO / ARISTÓTELES ───────────────────────
  {
    text: 'Conhece-te a ti mesmo.',
    author: 'Sócrates',
    reflection: 'Inscrita no templo de Apolo em Delfos, essa máxima resume uma das buscas mais antigas da filosofia. Conhecer a si mesmo — suas forças, seus limites, seus preconceitos, seus impulsos — é o fundamento de toda sabedoria prática. Sem esse conhecimento, tomamos decisões às cegas, reagimos por hábito e vivemos a vida de outro, não a nossa.',
    category: 'Autoconhecimento',
    tags: ['autoconhecimento', 'filosofia', 'reflexão', 'identidade'],
    language: 'pt',
  },
  {
    text: 'A vida não examinada não vale a pena ser vivida.',
    author: 'Sócrates',
    reflection: 'Viver sem reflexão é reproduzir automaticamente os padrões que herdamos sem jamais questioná-los. A vida examinada é aquela em que fazemos perguntas incômodas: Por que faço o que faço? Estou vivendo de acordo com meus valores? O que realmente importa para mim? Esse exame não paralisa — liberta, dando direção genuína à existência.',
    category: 'Autoconhecimento',
    tags: ['reflexão', 'filosofia', 'vida', 'propósito'],
    language: 'pt',
  },
  {
    text: 'Só sei que nada sei.',
    author: 'Sócrates',
    reflection: 'A sabedoria verdadeira começa com a consciência da própria ignorância. Quando reconhecemos que nosso conhecimento é sempre parcial e provisório, mantemos a mente aberta, a curiosidade viva e o julgamento humilde. Não é a ignorância que nos limita — é a ilusão de que sabemos quando na verdade não sabemos.',
    category: 'Sabedoria',
    tags: ['humildade', 'sabedoria', 'ignorância', 'filosofia'],
    language: 'pt',
  },
  {
    text: 'Somos o que repetidamente fazemos. A excelência, portanto, não é um ato, mas um hábito.',
    author: 'Aristóteles',
    reflection: 'O caráter não é construído em momentos extraordinários, mas em decisões ordinárias repetidas dia após dia. A excelência não surge de uma única escolha heroica — ela é destilada de centenas de escolhas pequenas e consistentes ao longo do tempo. Pergunte-se: o que estou repetindo hoje que está moldando quem serei amanhã?',
    category: 'Autodisciplina',
    tags: ['hábito', 'excelência', 'disciplina', 'caráter'],
    language: 'pt',
  },
  {
    text: 'Educar a mente sem educar o coração não é educação alguma.',
    author: 'Aristóteles',
    reflection: 'A inteligência sem empatia produz competência sem sabedoria. A formação humana plena une o rigor intelectual à sensibilidade moral — a capacidade de pensar com precisão e de agir com bondade. No mundo de hoje, onde a expertise técnica é valorizada acima de tudo, este lembrete é mais necessário do que nunca.',
    category: 'Virtude',
    tags: ['educação', 'coração', 'mente', 'sabedoria'],
    language: 'pt',
  },
  {
    text: 'A felicidade é a atividade da alma de acordo com a virtude.',
    author: 'Aristóteles',
    reflection: 'Eudaimonia — a florescência humana que Aristóteles descrevia — não é uma sensação passageira de prazer, mas o resultado de viver em alinhamento com nossa natureza mais elevada. Quando agimos com virtude — com coragem, justiça, moderação e sabedoria — a felicidade é quase uma consequência natural desse alinhamento.',
    category: 'Virtude',
    tags: ['felicidade', 'virtude', 'alma', 'florescimento'],
    language: 'pt',
  },

  // ── CARLOS TORRES PASTORINO ────────────────────────────────
  {
    text: 'Um minuto de meditação vale mais do que uma hora de conversa vazia.',
    author: 'Carlos Torres Pastorino',
    reflection: 'A qualidade de nossa atenção é mais valiosa do que a quantidade de nossas atividades. Num único minuto de silêncio verdadeiro — onde a mente para, observa e ouve —, mais pode ser revelado do que em horas de ruído social. A meditação não é uma pausa da vida: é o momento em que a vida se torna mais real.',
    category: 'Foco',
    tags: ['meditação', 'silêncio', 'qualidade', 'atenção'],
    language: 'pt',
  },
  {
    text: 'O medo não é inimigo da coragem. É o seu ponto de partida.',
    author: 'Carlos Torres Pastorino',
    reflection: 'A coragem não é a ausência de medo — é a decisão de agir apesar dele. Todo ato verdadeiramente corajoso começa com tremor. Quem nunca sentiu medo nunca precisou ser corajoso. Ao reconhecer o medo como ponto de partida, deixamos de nos julgar fracos por senti-lo e começamos a nos perguntar: o que farei agora que o reconheço?',
    category: 'Coragem',
    tags: ['coragem', 'medo', 'ação', 'crescimento'],
    language: 'pt',
  },
  {
    text: 'A gratidão transforma o que temos em suficiente.',
    author: 'Carlos Torres Pastorino',
    reflection: 'A percepção de escassez e a percepção de abundância frequentemente habitam o mesmo conjunto de circunstâncias. A diferença está no ângulo do olhar. Quando praticamos gratidão genuína — não como um exercício superficial, mas como uma mudança real de perspectiva —, o que antes parecia pouco revela-se pleno de valor. O suficiente já estava aqui; a gratidão o revelou.',
    category: 'Gratidão',
    tags: ['gratidão', 'abundância', 'perspectiva', 'contentamento'],
    language: 'pt',
  },

  // ── VIKTOR FRANKL ──────────────────────────────────────────
  {
    text: 'Entre o estímulo e a resposta há um espaço. Nesse espaço está nosso poder de escolher nossa resposta.',
    author: 'Viktor Frankl',
    reflection: 'Este espaço entre o que nos acontece e o que fazemos com isso é o campo onde a liberdade humana se manifesta. Embora não possamos controlar os estímulos que a vida nos envia, podemos — com prática e consciência — ampliar esse espaço e escolher respostas mais alinhadas com nossos valores. É ali que reside a dignidade incoercível do ser humano.',
    category: 'Autoconhecimento',
    tags: ['escolha', 'liberdade', 'resposta', 'consciência'],
    language: 'pt',
  },
  {
    text: 'Quem tem um porquê para viver pode suportar quase qualquer como.',
    author: 'Viktor Frankl',
    reflection: 'O propósito é a estrutura que sustenta o ser humano mesmo nas condições mais adversas. Frankl descobriu isso nos campos de concentração: aqueles que encontravam sentido — no amor, numa missão, numa ideia — sobreviviam onde outros desistiam. O propósito não elimina o sofrimento, mas lhe dá uma direção — e isso muda tudo.',
    category: 'Resiliência',
    tags: ['propósito', 'sentido', 'resiliência', 'vida'],
    language: 'pt',
  },
  {
    text: 'A última das liberdades humanas é a escolha da própria atitude frente a qualquer conjunto de circunstâncias.',
    author: 'Viktor Frankl',
    reflection: 'Por mais que as circunstâncias nos constranjam — e Frankl viveu as mais extremas que um ser humano pode enfrentar —, a escolha da atitude permanece. Não é uma escolha fácil, nem automática: é conquistada com disciplina interior. Mas é a mais poderosa de todas, porque é a única que permanece verdadeiramente nossa.',
    category: 'Coragem',
    tags: ['liberdade', 'atitude', 'escolha', 'circunstância'],
    language: 'pt',
  },

  // ── OUTROS FILÓSOFOS ───────────────────────────────────────
  {
    text: 'Vai com confiança na direção dos teus sonhos. Vive a vida que imaginaste.',
    author: 'Henry David Thoreau',
    reflection: 'A confiança de que fala Thoreau não é a certeza de que nada dará errado — é a disposição de seguir em frente mesmo sem essa certeza. Muitas pessoas vivem a vida que outros imaginaram para elas, por medo ou inércia. Viver a vida que você mesmo imaginou exige coragem, mas também exige primeiro imaginar — com clareza e honestidade — o que você realmente quer.',
    category: 'Coragem',
    tags: ['sonho', 'confiança', 'vida', 'propósito'],
    language: 'pt',
  },
  {
    text: 'Simplifica, simplifica, simplifica.',
    author: 'Henry David Thoreau',
    reflection: 'A vida acumula camadas de complicação com o tempo: compromissos desnecessários, posses que demandam manutenção, relações que drenam mais do que alimentam. Thoreau passou dois anos numa cabana na floresta para descobrir o que era essencial. Não precisamos ir tão longe — mas podemos perguntar, hoje: o que posso simplificar para ter mais espaço para o que realmente importa?',
    category: 'Foco',
    tags: ['simplicidade', 'minimalismo', 'essencial', 'clareza'],
    language: 'pt',
  },
  {
    text: 'Onde quer que você vá, vá com todo o seu coração.',
    author: 'Confúcio',
    reflection: 'A presença plena é o antídoto para a mediocridade. Fazer as coisas pela metade — com um olho no que poderíamos estar fazendo em vez disso — produz resultados pela metade e experiências ocas. Quando nos entregamos inteiramente ao que estamos fazendo, não apenas os resultados melhoram: a própria experiência se torna mais rica e mais memorável.',
    category: 'Foco',
    tags: ['presença', 'comprometimento', 'inteireza', 'foco'],
    language: 'pt',
  },
  {
    text: 'Nossa maior glória não está em nunca cair, mas em nos levantar toda vez que caímos.',
    author: 'Confúcio',
    reflection: 'A queda é inevitável; o levantamento é uma escolha. E é nessa escolha repetida — especialmente quando estamos exaustos, envergonhados ou sem esperança — que o verdadeiro caráter se revela e se fortalece. A resiliência não é uma qualidade com que nascemos: é uma prática que exercemos cada vez que decidimos tentar novamente.',
    category: 'Persistência',
    tags: ['resiliência', 'persistência', 'falha', 'levantamento'],
    language: 'pt',
  },
  {
    text: 'Somos o que repetidamente fazemos. A excelência, portanto, não é um ato, mas um hábito.',
    author: 'Platão',
    reflection: 'O início de qualquer empreitada define muito de seu rumo. Começos realizados com intenção clara e cuidado genuíno constroem bases sólidas. Quando iniciamos com descuido ou pressa, raramente conseguimos recuperar o terreno perdido. Hoje, se há algo a começar, comece da forma que gostaria de prosseguir.',
    category: 'Persistência',
    tags: ['início', 'trabalho', 'intenção', 'fundação'],
    language: 'pt',
  },
  {
    text: 'O melhor momento para plantar uma árvore foi há 20 anos. O segundo melhor momento é agora.',
    author: 'Provérbio Chinês',
    reflection: 'Não importa quanto tempo foi perdido: o passado não pode ser recuperado, mas o presente pode ser aproveitado. Ficar ruminando sobre as oportunidades perdidas é desperdiçar as oportunidades presentes. A única ação possível é sempre no agora — e agora é exatamente quando você pode começar.',
    category: 'Persistência',
    tags: ['ação', 'presente', 'começo', 'urgência'],
    language: 'pt',
  },
  {
    text: 'A disciplina é a ponte entre metas e realizações.',
    author: 'Jim Rohn',
    reflection: 'Ter objetivos sem disciplina é ter mapas sem as pernas para caminhar. A disciplina não é punição — é a capacidade de honrar seus compromissos com você mesmo mesmo quando a motivação vai embora, o entusiasmo esfria e o conforto chama mais alto. É exatamente nessas horas que a ponte é mais necessária.',
    category: 'Autodisciplina',
    tags: ['disciplina', 'metas', 'realização', 'consistência'],
    language: 'pt',
  },
  {
    text: 'Você não pode controlar o vento, mas pode ajustar suas velas.',
    author: 'Provérbio',
    reflection: 'A sabedoria prática está em distinguir o que está em nosso poder do que está além dele. As circunstâncias externas — o mercado, o clima, a saúde, o comportamento dos outros — são como o vento: mudam sem pedir permissão. Mas a forma como respondemos a essas circunstâncias — nossas velas — está sempre em nossas mãos.',
    category: 'Resiliência',
    tags: ['adaptação', 'controle', 'resiliência', 'flexibilidade'],
    language: 'pt',
  },
  {
    text: 'Seja a mudança que você quer ver no mundo.',
    author: 'Mahatma Gandhi',
    reflection: 'A transformação do mundo começa onde sempre começou: em cada indivíduo. Quando exigimos dos outros uma conduta que não praticamos, perdemos credibilidade e eficácia. Mas quando incorporamos os valores que defendemos — honestidade, compaixão, coragem — tornamo-nos um argumento vivo que inspira sem a necessidade de palavras.',
    category: 'Virtude',
    tags: ['mudança', 'integridade', 'exemplo', 'virtude'],
    language: 'pt',
  },
  {
    text: 'Ninguém pode te fazer sentir inferior sem o teu consentimento.',
    author: 'Eleanor Roosevelt',
    reflection: 'A opinião que os outros têm de nós tem o poder que lhes concedemos. Quando construímos nossa autoestima sobre a aprovação alheia, ficamos eternamente reféns dos humores e julgamentos de outros. Quando a fundamentamos em nossos próprios valores e ações, encontramos uma estabilidade que nenhuma crítica pode abalar completamente.',
    category: 'Autoconhecimento',
    tags: ['autoestima', 'aprovação', 'identidade', 'dignidade'],
    language: 'pt',
  },
  {
    text: 'A liderança não é sobre ser o melhor. É sobre fazer os outros se tornarem melhores.',
    author: 'Anônimo',
    reflection: 'A verdadeira liderança não se mede por títulos ou resultados individuais, mas pela capacidade de elevar aqueles ao redor. Um líder que cresce sozinho edificou pouco. Um líder que cria condições para que outros floresçam deixa um legado que transcende a sua própria presença. Pergunte-se: quem ao meu redor se tornou melhor por causa da minha influência?',
    category: 'Liderança',
    tags: ['liderança', 'crescimento', 'influência', 'legado'],
    language: 'pt',
  },
  {
    text: 'A sabedoria está em saber o que ignorar.',
    author: 'William James',
    reflection: 'Vivemos numa era de excesso de informação e estímulo. A capacidade de discernir o que merece atenção — e deliberadamente ignorar o resto — tornou-se uma habilidade de sobrevivência. Sabedoria não é processar tudo: é saber filtrar. O que você está escolhendo ignorar hoje para poder dar atenção genuína ao que realmente importa?',
    category: 'Foco',
    tags: ['sabedoria', 'foco', 'filtro', 'atenção'],
    language: 'pt',
  },
  {
    text: 'Compara-te somente com quem eras ontem.',
    author: 'Jordan Peterson',
    reflection: 'A comparação com os outros é quase sempre infrutífera: comparamos nossas fraquezas invisíveis com as forças visíveis dos outros, num terreno sempre desequilibrado. A comparação mais útil é com a versão de si mesmo que existia ontem. Se você avançou — mesmo que minimamente —, o dia foi bem gasto.',
    category: 'Autoconhecimento',
    tags: ['comparação', 'crescimento', 'progresso', 'autoconhecimento'],
    language: 'pt',
  },
  {
    text: 'Faz o que é necessário, e depois o que é possível; de repente, estarás fazendo o impossível.',
    author: 'São Francisco de Assis',
    reflection: 'O caminho para o extraordinário quase sempre começa no ordinário. Não pela audácia, mas pela consistência. Quando fazemos com excelência o que é necessário — as tarefas simples, os compromissos básicos —, criamos a base de confiança e capacidade que nos permite gradualmente ampliar o possível até os limites do que parecia impossível.',
    category: 'Persistência',
    tags: ['necessário', 'possível', 'impossível', 'processo'],
    language: 'pt',
  },
  {
    text: 'O homem que move montanhas começa carregando pequenas pedras.',
    author: 'Confúcio',
    reflection: 'As grandes realizações são o resultado de um acúmulo de pequenas ações consistentes. Quem espera por um momento de grandeza para começar geralmente não começa nunca. Mas quem escolhe agir com excelência no pequeno — na tarefa de hoje, no hábito de amanhã — constrói, ao longo do tempo, algo que parecia impossível.',
    category: 'Persistência',
    tags: ['persistência', 'pequenos passos', 'consistência', 'grandeza'],
    language: 'pt',
  },
  {
    text: 'A paciência é amarga, mas seu fruto é doce.',
    author: 'Jean-Jacques Rousseau',
    reflection: 'Vivemos numa era de gratificação imediata que tornou a espera quase insuportável. Mas o que realmente vale — relacionamentos profundos, habilidades desenvolvidas, projetos bem construídos, sabedoria acumulada — exige tempo. A paciência não é passividade: é a confiança ativa de que o processo, se honrado, produzirá exatamente o que merece.',
    category: 'Persistência',
    tags: ['paciência', 'tempo', 'resultado', 'processo'],
    language: 'pt',
  },
  {
    text: 'A simplicidade é o máximo da sofisticação.',
    author: 'Leonardo da Vinci',
    reflection: 'Complexidade sem necessidade é um sinal de que ainda não compreendemos completamente aquilo que fazemos. A verdadeira maestria — em qualquer campo, seja arte, ciência ou vida pessoal — é capaz de expressar o essencial de forma clara, direta e elegante. Quando conseguimos simplificar sem perder substância, atingimos um nível de compreensão superior.',
    category: 'Sabedoria',
    tags: ['simplicidade', 'elegância', 'maestria', 'clareza'],
    language: 'pt',
  },
];
